services:
  rabbitmq:
    image: rabbitmq:4.1-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ms1:
    build: ./certificates-data-upload
    container_name: certificates-ms1
    depends_on:
      - rabbitmq
    ports:
      - "8081:8081"
  ms2:
    build: ./certificates-generator
    container_name: certificates-ms2
    depends_on:
      - rabbitmq
    volumes:
      - ./data/certificates:/app/certificates

  ms3:
    build: ./certificates-sender
    container_name: certificates-ms3

volumes:
  rabbitmq_data: