version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"      # porta para aplicações (Spring)
      - "15672:15672"    # painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
